server:
  port: 8081



##logging
logging:
  config: classpath:logback-spring.xml
  file: web-demo
  level: debug

##mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    log-prefix: dao.

pagehelper:
  autoDialect: true
  closeConn: true
  reasonable: true


##datasource
spring:
  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 300
    initialSize: 20
    maxWait: 6000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  freemarker:
    cache: false #为了热加载
    charset: utf-8
    content-type: text/html
    enabled: true
    number_format:
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: test