url:
  url: www.aa.com

mysql:
  url: jdbc:mysql://localhost:3306/xiche?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: 1234
